version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p.postgres
      - POSTGRES_ROOT_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
     - db:/var/lib/postgresql/data
     - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      genai-network:
        ipv4_address: 172.16.238.10
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - .docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - .docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      genai-network:
        ipv4_address: 172.16.238.20
volumes:
  db: 
networks:
  genai-network:
    ipam:
      config:
        - subnet: "172.16.238.0/24"