-- Raw reads table
DROP 
  TABLE IF EXISTS RAW_TAG_READ CASCADE;
CREATE TABLE IF NOT EXISTS RAW_TAG_READ (
  ID SERIAL PRIMARY KEY, 
  BATCH_ID VARCHAR(20), 
  PRODUCT_ID VARCHAR(255), 
  TAG_ID VARCHAR(255), 
  "TIMESTAMP" TIMESTAMP, 
  "VALUE" INT, 
  "STATUS" VARCHAR(20) DEFAULT 'NEW'
);
-- Batches table
DROP 
  TABLE IF EXISTS BATCHES CASCADE; 
CREATE TABLE IF NOT EXISTS BATCHES(
  ID SERIAL PRIMARY KEY, 
  BATCH_ID VARCHAR(20), 
  PRODUCT_ID VARCHAR(255), 
  START_TIME TIMESTAMP, 
  END_TIME TIMESTAMP, 
  "PARTITION" INT DEFAULT 1
);
-- Tags atble
DROP 
  TABLE IF EXISTS TAGS CASCADE;
CREATE TABLE IF NOT EXISTS TAGS (
  ID SERIAL PRIMARY KEY, 
  TAG_NAME VARCHAR(255), 
  PROCESSES BOOLEAN DEFAULT FALSE
);
-- Master Error Configuration of Tags
DROP 
  TABLE IF EXISTS TAG_CONFIGURATIONS CASCADE;
CREATE TABLE IF NOT EXISTS TAG_CONFIGURATIONS (
  ID SERIAL PRIMARY KEY, 
  MASTER_TAG_ID INT, 
  ERROR_TAG_ID INT
);
ALTER TABLE 
  TAG_CONFIGURATIONS 
ADD 
  CONSTRAINT FK_TAG_CONFIGURATIONS_MASTER_TAG FOREIGN KEY (MASTER_TAG_ID) REFERENCES TAGS(ID);
ALTER TABLE 
  TAG_CONFIGURATIONS 
ADD 
  CONSTRAINT FK_TAG_CONFIGURATIONS_ERROR_TAG FOREIGN KEY (ERROR_TAG_ID) REFERENCES TAGS(ID);
-- Relation table between raw data and batches
DROP
  TABLE IF EXISTS RAW_READ_BATCH_REL;
CREATE TABLE IF NOT EXISTS RAW_READ_BATCH_REL(
  RAW_ID INT,
  BATCH_ID INT
);
ALTER TABLE RAW_READ_BATCH_REL
ADD
  CONSTRAINT FK_RAW_READ_BATCH_REL_RAW FOREIGN KEY (RAW_ID) REFERENCES RAW_TAG_READ(ID);

ALTER TABLE RAW_READ_BATCH_REL
ADD
  CONSTRAINT FK_RAW_READ_BATCH_REL_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BATCHES(ID);
-- Relation table between raw data and tags
DROP
  TABLE IF EXISTS RAW_READ_TAG_REL;
CREATE TABLE IF NOT EXISTS RAW_READ_TAG_REL(
  RAW_ID INT,
  TAG_ID INT
);
ALTER TABLE RAW_READ_TAG_REL
ADD
  CONSTRAINT FK_RAW_READ_TAG_REL_RAW FOREIGN KEY (RAW_ID) REFERENCES RAW_TAG_READ(ID);

ALTER TABLE RAW_READ_TAG_REL
ADD
  CONSTRAINT FK_RAW_READ_TAG_REL_TAG FOREIGN KEY (TAG_ID) REFERENCES TAGS(ID);
-- Raw Interpolated Table
DROP 
  TABLE IF EXISTS RAW_INTERPOLATED CASCADE;
CREATE TABLE IF NOT EXISTS RAW_INTERPOLATED (
  ID SERIAL PRIMARY KEY, 
  "TIMESTAMP" TIMESTAMP, 
  "VALUE" INT, 
  "TYPE" VARCHAR(15)
);
-- Relation Table Between Raw Interpolate Data and Tags
DROP 
  TABLE IF EXISTS RAW_INTERPOLATED_TAGS_REL CASCADE;
CREATE TABLE IF NOT EXISTS RAW_INTERPOLATED_TAGS_REL(
  RAW_INTERPOLATE_ID INT NOT NULL, 
  TAG_ID INT NOT NULL
);
ALTER TABLE 
  RAW_INTERPOLATED_TAGS_REL 
ADD 
  CONSTRAINT FK_RAW_INTERPOLATED_TAGS_RAW FOREIGN KEY (RAW_INTERPOLATE_ID) REFERENCES RAW_INTERPOLATED(ID);
ALTER TABLE 
  RAW_INTERPOLATED_TAGS_REL 
ADD 
  CONSTRAINT FK_RAW_INTERPOLATED_TAGS_TAG FOREIGN KEY (TAG_ID) REFERENCES TAGS(ID);
-- Relation Table Between Raw Interpolate and Batches
CREATE TABLE IF NOT EXISTS RAW_INTERPOLATED_BATCHES_REL(
  RAW_INTERPOLATE_ID INT NOT NULL, 
  BATCH_ID INT NOT NULL
);
ALTER TABLE 
  RAW_INTERPOLATED_BATCHES_REL 
ADD 
  CONSTRAINT FK_RAW_INTERPOLATED_BATCHES_RAW FOREIGN KEY (RAW_INTERPOLATE_ID) REFERENCES RAW_INTERPOLATED(ID);
ALTER TABLE 
  RAW_INTERPOLATED_BATCHES_REL 
ADD 
  CONSTRAINT FK_RAW_INTERPOLATED_BATCHES_TAG FOREIGN KEY (BATCH_ID) REFERENCES BATCHES(ID);
-- Base moving average Table
DROP 
  TABLE IF EXISTS BASE_MOVING_AVERAGE CASCADE;
CREATE TABLE IF NOT EXISTS BASE_MOVING_AVERAGE(
  ID SERIAL PRIMARY KEY, 
  START_TIME TIMESTAMP, 
  END_TIME TIMESTAMP, 
  TOTAL_START INT, 
  TOTAL_END INT, 
  ERROR_START INT, 
  ERROR_END INT, 
  "SIZE" INT, 
  ERRORS INT, 
  ERROR_RATE REAL
);
DROP 
  TABLE IF EXISTS BASE_MOVING_AVERAGE_CONF_REL CASCADE;
CREATE TABLE IF NOT EXISTS BASE_MOVING_AVERAGE_CONF_REL(
  BASE_MA_ID INT NOT NULL, 
  CONFIG_ID INT NOT NULL
);
ALTER TABLE 
  BASE_MOVING_AVERAGE_CONF_REL 
ADD 
  CONSTRAINT FK_TAG_CONFIGURATIONS_REL_BASE FOREIGN KEY (BASE_MA_ID) REFERENCES BASE_MOVING_AVERAGE(ID);
ALTER TABLE 
    BASE_MOVING_AVERAGE_CONF_REL 
ADD 
  CONSTRAINT FK_TAG_CONFIGURATIONS_REL_CONF FOREIGN KEY (CONFIG_ID) REFERENCES TAG_CONFIGURATIONS(ID);
DROP 
  TABLE IF EXISTS BASE_MOVING_AVERAGE_BATCHES_REL CASCADE;
CREATE TABLE IF NOT EXISTS BASE_MOVING_AVERAGE_BATCHES_REL(
  BASE_MA_ID INT NOT NULL, 
  BATCH_ID INT NOT NULL
);
ALTER TABLE 
  BASE_MOVING_AVERAGE_BATCHES_REL 
ADD 
  CONSTRAINT FK_BASE_MOVING_AVERAGE_BATCHES_RAW FOREIGN KEY (BASE_MA_ID) REFERENCES BASE_MOVING_AVERAGE(ID);
ALTER TABLE 
  BASE_MOVING_AVERAGE_BATCHES_REL 
ADD 
  CONSTRAINT FK_BASE_MOVING_AVERAGE_BATCHES_TAG FOREIGN KEY (BATCH_ID) REFERENCES BATCHES(ID);
-- Insert Sample Tag Data
INSERT INTO TAGS(TAG_NAME, PROCESSES) 
VALUES 
  (
    '2570/Ma_B.SLV.Counter.Counter0200', 
    TRUE
  );
INSERT INTO TAGS(TAG_NAME, PROCESSES) 
VALUES 
  (
    '2570/Ma_B.SLV.Counter.Counter0202', 
    TRUE
  );

-- Insert Sample Tag Configuration Data
INSERT INTO TAG_CONFIGURATIONS(MASTER_TAG_ID, ERROR_TAG_ID) 
VALUES 
  (
    (
      SELECT 
        ID 
      FROM 
        TAGS 
      WHERE 
        TAG_NAME = '2570/Ma_B.SLV.Counter.Counter0200'
    ), 
    (
      SELECT 
        ID 
      FROM 
        TAGS 
      WHERE 
        TAG_NAME = '2570/Ma_B.SLV.Counter.Counter0202'
    )
  );